### ISSUE TITLE
UI: Status bar sizing 

### ISSUE THREAD

**Issue by jobybenoit** [loansindi/metar-printer#12]
In  #9 , Status bar is encroaching on font size spinner box, see attached 
[img_3195](https://user-images.githubusercontent.com/38538937/40134982-9f9a27fc-5909-11e8-9137-f03d8afe571e.JPG)

**Comment by loansindi** [comment]
i don't know that there's much i can do about a user sizing the window too small for the elements in it

**Comment by jobybenoit** [comment]
Fair... I may have failed to realize that I could resize. I was basing on default size
