### ISSUE TITLE
Auto Caps

### ISSUE THREAD

**Issue by jobybenoit** [loansindi/metar-printer#2]
Typing an ICAO code in the 'Print Report' window that is not capitalized will lead to a 404 prinout

**Comment by loansindi** [comment]
#5

**Comment by jobybenoit** [comment]
Tested, still not translating to uppercase
![img_3194](https://user-images.githubusercontent.com/38538937/40017798-0616ea32-5780-11e8-8655-c7d292a30934.JPG)

**Comment by loansindi** [comment]
updated PR #5 - should be good to go.

Source of error was having separate functions for clicking the button vs. pressing enter.

**Comment by jobybenoit** [comment]
Tested, working with button push and enter press
